- hosts: all
  become: yes
  tasks:
  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: ./kaizen
      dest: /tmp
      remote_src: yes

  - name: create file
    shell: touch hello
      

  